
= COMMUNITY CONTRIBUTIONS

{empty} +

Students can contribute any content they deem valuable to the curriculum site. This content must be relative to the work and explain concepts needed in the curriculum projects. This content can be of any format be it an article, a link or a workshop video.

{empty} +

== Contribution Process

. Fork the https://github.com/wethinkcode/community-contributions-fundamentals[community-contributions-fundamentals] repository
. Clone the forked repository to a local folder on your machine
. Read the #Contributor's Guide# in the repository `ReadMe` to familiarize yourself with the necessary make commands
. Run `make install` in the terminal to install dependencies
. In the repository, navigate to `content/modules`
. Navigate to the project folder you wish to contribute to
. Navigate to the `pages` directory (if there is no `pages` directory, create one)
. Create an AsciiDoc file (e.g. `content.adoc`)
. Write your content in this AsciiDoc file using AsciiDoc syntax
. Add any images to the #images# folder in the same directory (if it does not exist, create one)
. Add a reference to the file in the #nav.adoc# file under the same directory (if it does not exist, create it)
. Example reference: `$$* xref:content.adoc[My Content Title]$$`
. Make sure that the `nav.adoc` in the folder is referenced in `antora.yml` under the `content` folder
. Run `make preview` in the terminal and open `localhost:8051` in your browser to view your changes
. Push your changes to your forked repository
. From your forked repository, create a pull request to add your content to the main repository
. Review any change requests and update your pull request
. Your content can be merged upon approval by another student

{empty} +

== Antora

The WeThinkCode curriculum site is built using a tool called #Antora#. Antora builds HTML and CSS files from AsciiDoc files. It is important to understand Antora and how it works to be able to contribute to the curriculum site effectively. 

Most important to know is how Antora expects the directory to be structured and how Antora builds the navigation using the #nav.adoc# files. The reading section links to the Antora documentation describing these processes and their requirements.

.icon:glasses[] Self Study
****
* https://docs.antora.org/antora/2.3/standard-directories/[Antora Standard File and Directory Set]
* https://docs.antora.org/antora/2.3/navigation/[Antora Navigation Assembly]
****

{empty} +

== AsciiDoc

Content for the WeThinkCode curriculum site is written in AsciiDoc format. AsciiDoc files require at least a title and a body. AsciiDoc also expects headings to be in order. It is important to understand AsciiDoc syntax to be able to write content effectively. The reading section refers to an AsciiDoc syntax cheat sheet that you can refer to when writing your documents.

It is recommended to have an understanding of:

* headers
* blocks
* text
* macros
* lists

TIP: To enter an empty line use #$${empty} +$$#

.icon:glasses[] Self Study
****
* https://powerman.name/doc/asciidoc[AsciiDoc Cheat Sheet]
****

== GitHub

If you are not sure how to fork a repository or create a pull request from a fork, below are some useful resources to guide you.

.icon:glasses[] Self Study
****
* https://docs.github.com/en/github/getting-started-with-github/quickstart/fork-a-repo[Fork a Repo]
* https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork[Create a Pull Request from a Fork]
****




