
= COMMUNITY CONTRIBUTIONS FUNDAMENTALS

:icons: image
:icontype: svg
:chapter: false
:menuTitle: COMMUNITY CONTRIBUTIONS FUNDAMENTALS
:pre: <b>101</b>
:sequence: 101
:uuid: 505079ba-4393-47ff-a956-330555b09f00
:weight: 10

{empty} +

This module is mandatory and teaches the foundations of programming.  Everything you learn here is necessary for programming anything.  For example, we use this foundational knowledge to program a mobile phone, a web application, or even machine learning systems and data science applications.

{empty} +

== Programming

icon:project-diagram[] Making Decisions:: How to make your program do different things based on the data it receives.
icon:redo[] Repeating Instructions:: How to get your program to do the same thing several times over.
icon:object-group[] Structuring Data:: How to work with more complex kinds of data structures.
icon:layer-group[] Combining Instructions:: Very often, we combine several instructions and reuse the combined instructions as a single instruction.
icon:bars[] Processing Collections of Data:: How to work with lists of the same kind of data in a variety of ways.
icon:cubes[] Modules and Packages:: How to use libraries from other developers (including open source libraries) and design a large program from smaller modules.

{empty} +

== Engineering

icon:cubes[] Build:: How to structure your code files and package them to be run.
icon:check-square[] Test:: How to write a program to test that your program works.

{empty} +

== Communications

icon:book[] Journaling:: This helps you reflect on your learning and articulate it. The more you do it, the better you get at communicating.
icon:users[] Presentations:: You will give short-form presentations known as https://en.wikipedia.org/wiki/PechaKucha[PechaKucha]. This helps you become comfortable at speaking in teams and in front of groups of people.

{empty} +

== Teamwork

icon:users-cog[] Group Project:: You will work in small teams to build a program that, ordinarily, is too much to do on your own.

